apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stripnoir-api
  namespace: stripnoir
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stripnoir-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
